const test=require('node:test'),assert=require('node:assert/strict'),D=require('../miniprogram/shared/domain'),S=require('../miniprogram/shared/season');
const mon=Date.parse('2026-09-21T00:00:00+08:00');
function couple(){const r=D.room('r',{id:'a'},mon);r.members.push({id:'b'});return r;}
function run(r,actor,action,p,now,id){return S.track(r,D.apply(r,actor,action,p,now,id),now);}
function complete(r,at,id){r=run(r,'a','start',{type:'music'},at,id);r=run(r,'b','joinActivity',{id},at);r=run(r,'a','finish',{id},at);return run(r,'b','finish',{id},at);}
test('weekly ledger survives journal truncation, repeated activities and repeated finish',()=>{let r=couple();r=complete(r,mon,'one');r.records=[];r=complete(r,mon+1000,'two');r=run(r,'b','finish',{id:'two'},mon+1001);assert.equal(r.seasonLedger.points,4);assert.equal(r.seasonLedger.count,2);assert.equal(r.seasonLedger.days.length,1);assert.equal(r.seasonLedger.types.find(x=>x.id==='music').points,4);});
test('Monday closes previous week and new activity counts only in new week',()=>{let r=complete(couple(),mon,'old');const old=S.row(r,mon,'pair');r=complete(r,mon+7*86400000,'new');assert.equal(S.previous(mon+7*86400000),'2026-09-21');assert.equal(old.points,4);assert.equal(r.seasonLedger.key,'2026-09-28');assert.equal(r.seasonLedger.points,4);assert.equal(r.total,8);});
test('no early reward, tie ranking and private participant still earns milestone',()=>{const row={id:'r',points:40,count:5,days:3,types:[],listed:true};const before=S.report(row,[row,{id:'b',points:40}],'2026-09-21',mon,false);assert.equal(before.finished,false);assert.equal(before.canClaim,false);const after=S.report(row,[row,{id:'b',points:40}],'2026-09-21',mon+7*86400000,false);assert.equal(after.rank,1);assert.equal(after.reward.name,'默契生长');assert.equal(after.canClaim,true);const privateReport=S.report({...row,listed:false},[],'2026-09-21',mon+7*86400000,true);assert.equal(privateReport.rank,0);assert.equal(privateReport.claimed,true);assert.equal(privateReport.canClaim,false);});
test('empty week has no invented award or rank',()=>{const report=S.report(null,[],'2026-09-21',mon+7*86400000,false);assert.equal(report.reward,null);assert.equal(report.rank,0);assert.equal(report.hasData,false);assert.equal(report.canClaim,false);});

test('week selection validates Monday and bounds, refusing early claims and future weeks',()=>{assert.throws(()=>S.resolveKey({key:'2026-09-21'},mon,true));assert.throws(()=>S.resolveKey({key:'2026-09-28'},mon,false));assert.throws(()=>S.resolveKey({key:'2026-09-20'},mon,false));assert.throws(()=>S.resolveKey({key:'2025-09-22'},mon,true));assert.equal(S.resolveKey({key:'2026-09-14'},mon,true),'2026-09-14');});
