// Presentation-only decorator. Original authentication, storage, scoring and course math stay intact.
module.exports=function visualUI(page){
 Object.assign(page.data,{uiPanels:{},spaceWishText:'',spaceEditor:false,uiCalendar:[],uiRecords:[],uiMonth:'',uiMonthOffset:0,uiJournalDay:'',uiRecord:null,uiCourseRange:'',uiScoreRows:[],uiTimerStyle:'',uiOtherBar:'',uiOwnBar:'',uiBoard:[],uiDetailAvatar:0,uiPodium:[],uiBoardRest:[]});
 page.uiToggle=function(e){const key=e.currentTarget.dataset.key;this.setData({uiPanels:Object.assign({},this.data.uiPanels,{[key]:!this.data.uiPanels[key]})});};
 page.uiRefresh=function(){const d=this.data,r=d.room;if(!r)return;if(this.uiRoomId&&this.uiRoomId!==r.id){this.setData({uiJournalDay:'',uiRecord:null});}this.uiRoomId=r.id;const active=r.active,type=active&&(d.types||[]).find(t=>t.id===active.type),progress=active&&active.startedAt!==null?(type&&type.minutes?Math.max(0,Math.min(1,1-active.remaining/type.minutes)):1):0;const compareMax=Math.max(1,r.weekPoints||0,d.detail&&d.detail.points||0);const allRows=(d.board||[]).slice(0,100).map(x=>Object.assign({},x,{uiAvatar:Array.from(x.id).reduce((v,c)=>v+c.charCodeAt(0),0)%8}));const now=new Date(),date=new Date(now.getFullYear(),now.getMonth()+d.uiMonthOffset,1),year=date.getFullYear(),month=date.getMonth(),last=new Date(year,month+1,0).getDate(),pad=(date.getDay()+6)%7;const key=n=>year+'-'+String(month+1).padStart(2,'0')+'-'+String(n).padStart(2,'0');const records=r.records||[];const normalized=x=>(x.date||'').replace(/\./g,'-');const calendar=Array.from({length:Math.ceil((pad+last)/7)*7},(_,i)=>{const n=i-pad+1;if(n<1||n>last)return {id:'blank-'+i,blank:true};const items=records.filter(x=>normalized(x)===key(n));return {id:key(n),day:n,type:items[0]&&items[0].type,count:items.length,selected:d.uiJournalDay===key(n),today:key(n)===key(now.getDate())&&month===now.getMonth()&&year===now.getFullYear()};});const visible=(d.visibleRecords||records).filter(x=>!d.uiJournalDay||normalized(x)===d.uiJournalDay);const max=Math.max(1,...(d.scoreRows||[]).map(x=>x.earned));this.setData({uiSpaceProgress:'width:'+(r.spaceView ? r.spaceView.progress : 0)+'%;',uiPodium:allRows.slice(0,3).map((x,i)=>Object.assign({},x,{uiSlot:i})).sort((a,b)=>[1,0,2].indexOf(a.uiSlot)-[1,0,2].indexOf(b.uiSlot)),uiBoardRest:allRows.slice(3),uiDetailAvatar:Array.from(d.detail&&d.detail.id||'').reduce((v,c)=>v+c.charCodeAt(0),0)%8,uiBoard:(d.board||[]).slice(0,100).map(x=>Object.assign({},x,{uiAvatar:Array.from(x.id).reduce((v,c)=>v+c.charCodeAt(0),0)%8})),uiTimerStyle:'transform:rotate('+Math.round(progress*360)+'deg);',uiOtherBar:'width:'+Math.round((d.detail&&d.detail.points||0)/compareMax*100)+'%;',uiOwnBar:'width:'+Math.round((r.weekPoints||0)/compareMax*100)+'%;',uiCalendar:calendar,uiMonth:(month+1)+'月',uiYear:year,uiRecords:visible,uiScoreRows:(d.scoreRows||[]).map(x=>Object.assign({},x,{bar:'width:'+Math.round(x.earned/max*100)+'%;'})),uiCourseRange:d.courseDays&&d.courseDays.length?d.courseDays[0].date.slice(5).replace('-','.')+' — '+d.courseDays[6].date.slice(5).replace('-','.'):''});};
 page.uiMonthShift=function(e){this.setData({uiMonthOffset:this.data.uiMonthOffset+Number(e.currentTarget.dataset.delta),uiJournalDay:''});this.uiRefresh();};
 page.uiPickDay=function(e){const day=e.currentTarget.dataset.id;this.setData({uiJournalDay:this.data.uiJournalDay===day?'':day});this.uiRefresh();};
 page.uiOpenRecord=function(e){this.setData({uiRecord:this.data.room.records.find(x=>x.id===e.currentTarget.dataset.id)||null});};
 page.uiCloseRecord=function(){this.setData({uiRecord:null});};
 page.uiEditRecord=function(){const id=this.data.uiRecord&&this.data.uiRecord.id;this.setData({uiRecord:null});if(id)this.edit({currentTarget:{dataset:{id}}});};
 page.uiDatePlan=function(){this.tab({currentTarget:{dataset:{tab:this.data.room.paired?'datePlan':'pair'}}});};
 page.spaceSpark=function(){return this.request('spaceSpark');};
 page.spaceDate=function(e){return this.request('spaceAnniversary',{date:e.detail.value});};
 page.spaceWishInput=function(e){this.setData({spaceWishText:e.detail.value});};
 page.spaceWishEditor=function(){this.setData({spaceEditor:!this.data.spaceEditor,spaceWishText:''});};
 page.spaceWishSave=async function(){if(await this.request('spaceWish',{text:this.data.spaceWishText}))this.setData({spaceWishText:'',spaceEditor:false});};
 page.spaceWishToggle=function(e){return this.request('spaceWish',{id:e.currentTarget.dataset.id,done:!(e.currentTarget.dataset.done===true||e.currentTarget.dataset.done==='true')});};
 page.spaceWishRemove=function(e){return this.request('spaceWish',{id:e.currentTarget.dataset.id,remove:true});};
 const open=page.openCouple;page.openCouple=function(e){if(!e.currentTarget.dataset.id||e.currentTarget.dataset.id===this.data.room.id){this.tab({currentTarget:{dataset:{tab:'home'}}});return this.refresh();}return open.call(this,e);};
 const request=page.request;page.request=async function(...args){const result=await request.apply(this,args);this.uiRefresh();return result;};
 for(const key of ['updateCourses','updateImportGrid','filterRecords','openCouple']){const fn=page[key];if(fn)page[key]=function(...args){if(key==='filterRecords')this.setData({uiJournalDay:''});const result=fn.apply(this,args);this.uiRefresh();return result;};}
 return page;
};
